import { Jersey } from './types';

export const JERSEYS: Jersey[] = [
  {
    id: 'brazil-2026',
    country: 'Brazil',
    name: 'Brazil 2026 Authentic Home Jersey',
    priceBDT: 1450,
    priceUSD: 14,
    image: '/input_file_3.png',
    description: 'Embrace the soul of Joga Bonito. The 2026 edition features an organic canvas pattern embodying Brazil’s rainforest layers, completed with a performance-driven flat-knit green collar and elastic sleeves.',
    rating: 4.9,
    reviewsCount: 142,
    badgeColor: 'bg-[#009b3a] text-white',
    accentColor: 'text-yellow-400',
    bgGradient: 'from-amber-500/10 via-green-600/5 to-slate-950',
  },
  {
    id: 'argentina-2026',
    country: 'Argentina',
    name: 'Argentina 2026 Three-Star Home Jersey',
    priceBDT: 1400,
    priceUSD: 13,
    image: '/input_file_1.png',
    description: 'Rich in history, designed for champions. Crafted with Argentine sky blue and alabaster vertical stripes, integrated with championship gold borders, and crowned by the iconic three golden stars crest.',
    rating: 4.8,
    reviewsCount: 198,
    badgeColor: 'bg-[#74acdf] text-white',
    accentColor: 'text-[#74acdf]',
    bgGradient: 'from-[#74acdf]/10 via-amber-400/5 to-slate-950',
  },
  {
    id: 'bangladesh-2026',
    country: 'Bangladesh',
    name: 'Bangladesh 2026 Gold Edition Home Jersey',
    priceBDT: 1350,
    priceUSD: 12,
    image: '/input_file_2.png',
    description: 'Celebrate the pride of the Bengal Tigers. This premium 2026 edition features a dynamic red and green abstract canvas with geometric lines, completed with a solid crimson collar and high-definition Bangladesh football federation crest.',
    rating: 4.9,
    reviewsCount: 224,
    badgeColor: 'bg-[#006a4e] text-white',
    accentColor: 'text-red-500',
    bgGradient: 'from-emerald-600/10 via-red-650/5 to-slate-950',
  },
  {
    id: 'japan-2026',
    country: 'Japan',
    name: 'Japan 2026 Special Edition Anime Jersey',
    priceBDT: 1490,
    priceUSD: 14.5,
    image: '/input_file_4.png',
    description: 'Where anime fantasy meets elite pitch performance. Engineered with custom dark ink patterns, featuring a highly-detailed Itachi and Akatsuki-crossover manga character illustration integrated right into the knit paneling.',
    rating: 5.0,
    reviewsCount: 312,
    badgeColor: 'bg-red-600 text-white',
    accentColor: 'text-red-500',
    bgGradient: 'from-red-600/10 via-zinc-850/5 to-slate-950',
  },
  {
    id: 'france-2026',
    country: 'France',
    name: 'France 2026 Royal Crest Home Jersey',
    priceBDT: 1500,
    priceUSD: 15,
    image: '/src/assets/images/france_jersey_2026_1779474568262.png',
    description: 'Sleek French elegance meets high-performance engineering. Featuring a majestic metallic royal blue base, textured honeycomb details, and an imposing gilded oversized cockerel crest.',
    rating: 4.9,
    reviewsCount: 125,
    badgeColor: 'bg-[#002395] text-white',
    accentColor: 'text-blue-400',
    bgGradient: 'from-blue-600/10 via-red-600/5 to-slate-950',
  },
  {
    id: 'spain-2026',
    country: 'Spain',
    name: 'Spain 2026 La Furia Roja Home Jersey',
    priceBDT: 1350,
    priceUSD: 12.5,
    image: '/input_file_0.png',
    description: 'Feel the heat of La Furia Roja. Imbued with a striking scarlet red hue and fluid gold side piping, complete with Spain’s newly minted coat-of-arms in minimalist monochrome finish.',
    rating: 4.7,
    reviewsCount: 94,
    badgeColor: 'bg-[#c60b1e] text-white',
    accentColor: 'text-red-500',
    bgGradient: 'from-red-600/10 via-yellow-500/5 to-slate-950',
  },
  {
    id: 'portugal-2026',
    country: 'Portugal',
    name: 'Portugal 2026 Navigator Home Jersey',
    priceBDT: 1480,
    priceUSD: 14.5,
    image: '/src/assets/images/portugal_jersey_2026_1779474611877.png',
    description: 'Honoring the legacy of Portuguese maritime discoverers. Clad in luxurious dark burgundy red, with high-definition deep pine-green borders and elegant gold nautical motifs.',
    rating: 4.9,
    reviewsCount: 167,
    badgeColor: 'bg-[#046a38] text-white',
    accentColor: 'text-[#d01c1f]',
    bgGradient: 'from-emerald-600/10 via-red-600/5 to-slate-950',
  },
  {
    id: 'germany-2026',
    country: 'Germany',
    name: 'Germany 2026 Modernist Home Jersey',
    priceBDT: 1380,
    priceUSD: 13.5,
    image: '/src/assets/images/germany_jersey_2026_1779474631424.png',
    description: 'Architectural precision in athletic wear. Features a stark clean white background accented by premium deep-black mesh trims and a subtle gradient of sovereign gold and red across the knit lines.',
    rating: 4.8,
    reviewsCount: 110,
    badgeColor: 'bg-black text-white',
    accentColor: 'text-slate-400',
    bgGradient: 'from-slate-600/10 via-amber-500/5 to-slate-950',
  },
];
